#pragma once

// Main

#define TEXT_MAIN_START "PRESS START"
#define TEXT_NEW_GAME "NEW GAME"

// Pre-Dungeon

#define TEXT_PREP "PREPARATIONS"
#define TEXT_INN "INN"
#define TEXT_TAVERN "TAVERN"
#define TEXT_SHOP "SHOP"
#define TEXT_GUILD "GUILD"
#define TEXT_START "START DUNGEON"

#define TEXT_GO_BACK "BACK"

#define TEXT_TALK "TALK"

// Pre-Dungeon Inn

#define TEXT_GO_STAY "STAY"

// Pre-Dungeon Shop

#define TEXT_BUY "BUY"
#define TEXT_SELL "SELL"

// Pre-Dungeon Guild

#define TEXT_GUILD_ADD_MEMBER "ADD MEMBER"
#define TEXT_GUILD_RETIRE_MEMBER "RETIRE MEMBER"
#define TEXT_GUILD_ITEM_BAG "ITEM BAG"

#define TEXT_GUILD_ADD_MEMBER_NAME "NAME"
#define TEXT_GUILD_ADD_MEMBER_CLASS "CLASS"
#define TEXT_GUILD_ADD_MEMBER_GENDER "GENDER"
#define TEXT_GUILD_ADD_MEMBER_DONE "DONE"

#define TEXT_VACANT "-EMPTY-"
#define TEXT_NO_NAME "NO NAME"

// Class Names

#define TEXT_WARRIOR "WARRIOR"
#define TEXT_THIEF "THIEF"
#define TEXT_CLERIC "CLERIC"
#define TEXT_WIZARD "WIZARD"
#define TEXT_NO_CLASS "NO CLASS"

// Gender Names

#define TEXT_MALE "MALE"
#define TEXT_FEMALE "FEMALE"
#define TEXT_NO_GENDER "NO GENDER"

// Items

#define TEXT_ITEMS "ITEMS"
#define TEXT_SMALL_HEAL "SMALL HEAL"
#define TEXT_LARGE_HEAL "LARGE HEAL"

// Combat

#define TEXT_COMBAT_ATK "ATTACK"
#define TEXT_COMBAT_DEF "DEFEND"
#define TEXT_COMBAT_SKL "SKILL"
#define TEXT_COMBAT_ITM "ITEMS"
#define TEXT_COMBAT_RUN "RUN"
